### ISSUE TITLE
Hyperlinks pointing to wrong pages

### ISSUE THREAD

**Issue by maysamemadi** [rchurchley/thesis-template#13]
Just a minor issue. When using hyperref, some hyperlinks in the compiled pdf document point to the wrong page. That includes all links to front matter sections which send you to the first page, and links to bibliography and index to their respective previous (sub)section. Main matter links are fine. The page numbers listed in the table of contents are also correct.

Cause:
It's actually not a hyperref bug. The \addtoToC command does not automatically place an anchor for hyperref for these problem sections. So hyperref just uses the last anchor. Hence, misdirected targets pointing to preceding sections.

Suggested fix:
Using a \phantomsection command before each problem section fixes the issue by creating a hyperlink anchor. I had to make 10 phantom sections to get them all right. In every case it is followed by an \addtoToC command. So perhaps a better solution would be to prepend a \phantomsection to \addtoToC?

**Comment by rchurchley** [comment]
Good catch. Fixed in 0ed0d8c as you suggested, by prepending `\phantomsection` to `\addtoToC` when `hyperref` is loaded.
